### PR TITLE
fix: building issues and update deps

### PR DESCRIPTION
**Pull request by macnack**

### CODE REVIEW

**Comment by iKrishneel** [comment]
Thanks for the PR. Unfortunately it seems that `PCL 1.12` is having some issues 
```bash
Starting >>> octomap_server2
--- stderr: octomap_server2
CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a configuration file for package "PCL" that is compatible
  with requested version "1.12".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake, version: 1.10.0
    /lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake, version: 1.10.0



---
Failed   <<< octomap_server2 [1.65s, exited with code 1]
```

Could you take a look?

**Comment by macnack** [comment]
Hello, Im gonna take a look.
Sorry for the confusion, will solve this problem soon.

**Comment by macnack** [comment]
Hello, from my side evething is okay on humble. My couse is docker image with foxy... Checkout my branch with [docker](https://github.com/macnack/octomap_server2.git)

**Comment by iKrishneel** [comment]
@macnack thanks, I think its good time to migrate the ci to humble. I will do that soon and check the PR.

**Comment by iKrishneel** [comment]
@macnack 
Are open to support in maintaining this repo? If so, I will add you as a collaborator.

**Pull request merged**
